### ISSUE TITLE
'Open Preview' is not an option

### ISSUE THREAD

**Issue by buhtig2000** [jjuback/gc-excelviewer#68] opened 2018-06-19 01:31 UTC
Installed 2.0.21 fine on SV Code v.1.24.0.

When invoking the explorer context menu of a good xlsx file, I do not see "Open Preview" as an option.

Please advise.

**Comment by gennaro-tedesco** [comment] 2018-06-19 09:44
I have a similar issue on VSCode 1.24.0 as well, only it happens for `.csv` extensions. Somehow they are not recognised as such anymore; it plain text files, though, it still works as expected.

**Comment by jjuback** [comment] 2018-06-19 16:15
@gennaro-tedesco Are you also using the Rainbow CSV extension? There is a known issue where my extension looks for a language id of "csv" but that extension uses "CSV". I'm adding a fix for this in the next release.

**Comment by gennaro-tedesco** [comment] 2018-06-19 16:34
I do use the above mentioned extension: however, even after disabling it (or completely un-installing it) the problem still remains; strangely enough, even the "open preview" icon (usually positioned on the top right corner of the page) disappeared all of a sudden. 

Are there any general settings that should be re-configured or any more information we can provide you with, in order to better understand?

**Comment by jjuback** [comment] 2018-06-19 21:20
I can reproduce the problem for CSV files, but only if I enable the Rainbow extension. I think the next version (available in the next few days) will fix this issue.

**Comment by jjuback** [comment] 2018-06-20 19:23
@gennaro-tedesco @buhtig2000 Try version 2.1.23, which is more forgiving w.r.t. mixed case language ids.

**Comment by gennaro-tedesco** [comment] 2018-06-21 07:34
I have tried it and it seems to be working fine, opening the previews as expected.

**Closed** 2018-06-21 13:29 UTC
